var fib = funcion(numero) {
    si (numero <= 2) {
        regresa 1;
    } si_no {
        regresa fib(numero - 2) + fib(n - 1);
    }
}

var resultado = fib(10);
escribir(resultado);

var es_par = funcion(numero) {
    si (numero % 2 == 0) {
        regresa verdadero;
    } si_no {
        regresa falso;
    }
}

var resultado = es_par(3);
escribir(resultado);

var resultado = es_par(4);
escribir(resultado);

